spring.datasource.url=jdbc:postgresql://dpg-d89vigojo6nc73e864e0-a.oregon-postgres.render.com:5432/hmpsjf_2zwu

spring.datasource.username=snehanand

spring.datasource.password=xvV5IbZlCgIqtZd7haz294NcWCjJ2a5F

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080